# Generated by Django 3.2.12 on 2022-05-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='movie_bookmark',
            new_name='bookmark_movies',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='movie_like',
            new_name='like_movies',
        ),
    ]
