"""
Django settings for amu project.

Generated by 'django-admin startproject' using Django 3.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qwy@p@-#02ttb1hbo20_23(l2^icpdmid7ulo^^l50idb+nd%$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# django.contrib.sites 에서 등록 필요
SITE_ID = 1

# drf 설정
REST_FRAMEWORK = {
    # 기본 인증방식 설정
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',        
    ],

    # 기본 권한 설정
    'DEFAULT_PERMISSION_CLASSES': [        
        'rest_framework.permissions.AllowAny',      # => 기본적으로 모두에게 허용
        # 'rest_framework.permissions.IsAuthenticated', # => 기본적으로 인증받아야 허용 / 비인증 사용자는 모두 401 Unauthorized
    ]
}

# 특정 origin 에게만 교차 출처 허용
CORS_ALLOWED_ORIGINS = [
    # Vue LocalHost
    'http://localhost:8080',
]

# 모두에게 교차출처 허용 (*)
# CORS_ALLOW_ALL_ORIGINS = True

INSTALLED_APPS = [
    # Apps
    'accounts',
    'movies',
    'community',

    # 3rd party app
    'rest_framework',
    # token authentication
    'rest_framework.authtoken', # token 기반 auth

    # DRF auth 담당    
    'dj_rest_auth',              # signup 제외 auth 관련 담당
    'dj_rest_auth.registration', # signup 담당


    # django allauth / signup 담당을 위해 필요 
    'allauth',
    'allauth.account',
    # allauth 사용을 위해 필요
    'django.contrib.sites',

    # CORS 세팅
    'corsheaders',

    # django natvie app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    # CommonMiddleware보다 위에 위치
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/' # 사용자가 보는 미디어 url

AUTH_USER_MODEL = 'accounts.User'

# 필요한 유저 모델 관련 필드들을 유저와 1:N인 새로운 모델로 만들어주기로 함!!
# 했는데 이메일은 필수 필드로 만들기로 해서 커스텀 시리얼라이저 사용함!
# 커스텀 회원가입 시리얼라이저를 사용한다!!
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegistrationSerializer',
}

ACCOUNT_EMAIL_VERIFICATION = 'none'

# # 유저 정보를 저장하는 커스텀 어댑터 사용한다!!
# ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'