# Generated by Django 3.2.12 on 2022-05-18 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(null=True, related_name='article_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
